# Generated by Django 2.2.6 on 2020-12-11 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20201208_1911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
